#Database Configuration
server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.99.100:6432/pulse
    username: pulse
    password:
